app = 'typegg-stats'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'db_data'
  destination = '/app/src/data'

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 550
    soft_limit = 500

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
